-- ========================================================
-- MinionMP Supabase Database Initialization & Schema
-- Run this script in your Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New Query -> Run
-- ========================================================

-- 1. Create Parts Requests Table
CREATE TABLE IF NOT EXISTS public.minion_requests (
    id TEXT PRIMARY KEY,
    mechanic TEXT NOT NULL,
    tail TEXT NOT NULL,
    discrepancy TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'New',
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Catalog Annotations Table
CREATE TABLE IF NOT EXISTS public.minion_annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pdf_id TEXT NOT NULL,
    page_number INTEGER NOT NULL,
    shapes JSONB DEFAULT '[]'::jsonb,
    notes JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT minion_annotations_pdf_page_key UNIQUE (pdf_id, page_number)
);

-- 3. Create Part Inventory & Stock Location Table
CREATE TABLE IF NOT EXISTS public.minion_inventory (
    part_number TEXT PRIMARY KEY,
    nomenclature TEXT,
    qty_available INTEGER NOT NULL DEFAULT 0,
    location TEXT,
    unit TEXT DEFAULT 'EA',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create Part Images Mapping Table
CREATE TABLE IF NOT EXISTS public.minion_part_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create Shop Orders Table (For Ad-Hoc / Manual Sign-Outs)
CREATE TABLE IF NOT EXISTS public.minion_shop_orders (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    tail TEXT,
    mechanic TEXT,
    status TEXT NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ========================================================
-- Enable Row Level Security (RLS) & Allow Anonymous Access
-- ========================================================

ALTER TABLE public.minion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minion_annotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minion_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minion_part_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minion_shop_orders ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to SELECT, INSERT, UPDATE, DELETE
CREATE POLICY "Public anonymous access for minion_requests" ON public.minion_requests
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public anonymous access for minion_annotations" ON public.minion_annotations
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public anonymous access for minion_inventory" ON public.minion_inventory
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public anonymous access for minion_part_images" ON public.minion_part_images
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Public anonymous access for minion_shop_orders" ON public.minion_shop_orders
    FOR ALL USING (true) WITH CHECK (true);

-- ========================================================
-- Enable Supabase Realtime Replication
-- ========================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.minion_requests;
ALTER PUBLICATION supabase_realtime ADD TABLE public.minion_annotations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.minion_inventory;
ALTER PUBLICATION supabase_realtime ADD TABLE public.minion_shop_orders;

-- ========================================================
-- Storage Bucket Instructions for Image Uploads:
-- 1. Go to Supabase Dashboard -> Storage -> Create New Bucket
-- 2. Name: part-images
-- 3. Toggle "Public Bucket" to ON
-- ========================================================
